### PR TITLE
Add support for sending an array of arguments to a browser

### PR DESCRIPTION
**Pull request by skoshy**
This PR adds support for sending arguments to the browser. This allows for some cool stuff, like directly triggering a Chrome Application Shortcut and sending the URL to it.

```js
const googleMeetApp = {
  browser: ({ urlString }) => ({
    name: "Google Chrome",
    profile: "Profile 13", // use whatever profile created the application shortcut
    args: [
      `--app-id=jhgifngagadhdmngcahhimadjfofillb`, // my app ID for my Google Meet application shortcut
      `--app-launch-url-for-shortcuts-menu-item=${urlString}`,
      // notice I'm not passing urlString as an array entry, since Chrome Application Shortcuts don't like that
    ],
  }),
}

module.exports = {
  // ...
  handlers: [
    {
      match: finicky.matchHostnames(["meet.google.com"]),
      ...googleMeetApp,
    },
  ],
};
```

The PR adds a new key to the `browser` object:

- `args` - default: `[urlString]`. an array of string args to pass to the application.

Solves #153

### CODE REVIEW

**Comment by skoshy** [comment]
I'm considering getting rid of the `passUrlAsArg` param and instead defaulting `args` to be `[urlAsString]` when it's undefined. That way if someone needs to pass the url as an arg when setting `args`, they could just do

```js
args: [
  '-arg1=thing',
  urlAsString, // include this if you need the URL added as the last argument
]
```

Let me know if you think that's better!

**Comment by johnste** [comment]
This looks great! Merging now, will try to find some time to document all this. 
Thank you!

**Comment by johnste** [comment]
Released in [3.2.0](https://github.com/johnste/finicky/releases/tag/v3.2.0)

**Comment by Marbotine** [comment]
Hi guys !

Just a newbie here but massive fan of Finicky that has been running on my Mac since years. 

Having switched companies I now need to rely heavily on the google suite and I hate a bloated browser.

I discovered "web apps" today and to my delight, you guys have found a way to make it work 

I've spent a couple hours tweaking my config file but it's not working yet. Am I missing something in my config? 

`const googleMeetApp = {
  browser: ({ urlString }) => ({
    name: "Google Chrome",
    //profile: "Default", // use whatever profile created the application shortcut
    args: [
      `--app-id=kjgfgldnnfoeklkmfkjfagphfepbbdan`, // my app ID for my Google Meet application shortcut
      `--app-launch-url-for-shortcuts-menu-item=${urlString}`,
    ],
  }),
}


module.exports = {
  defaultBrowser: "Safari",

  handlers: [
    {
      // Open google Drive in Google Chrome
      match: [
        "docs.google.com/*", 
        "drive.google.com/*",
      ],
      browser: "Google Chrome"
    },
    {
      match: finicky.matchHostnames(["meet.google.com"]),
      ...googleMeetApp,
    }
  ]
};


`

**Pull request merged**
