### PR TITLE
add support for browser profiles

### PR DESCRIPTION
**Pull request by bhedavivek**
Allows selecting profile of target browser.
Adds support for Google Chrome, Brave Browser and Mozzila Firefox.

Apologies in advance for not following any Swift/Javascript conventions correctly. I don't don't have much experience in either.

You can specify which browser profile target by defining the profile property on the browser object in the config file.

### Sample Config
```
module.exports = {
    defaultBrowser: {
        name: "com.brave.Browser",
        appType: "bundleId",
        profile: "Personal",
        openInBackground: false,
    },
    handlers: [
        {
            match: ({ sourceProcessPath }) =>
                sourceProcessPath && sourceProcessPath.startsWith("/Applications/Slack.app"),
            browser: {
                name: "com.brave.Browser",
                appType: "bundleId",
                profile: "Work",
                openInBackground: false,
            }
        },
    ]
};
```

### CODE REVIEW

**Comment by johnste** [comment]
Hey,

Thanks for for working on this! There is [another pull request](https://github.com/johnste/finicky/pull/95) adding support for Google Chrome profiles which has a lot of similarity to your approach, though it doesn't attempt to add profile support for Brave or Firefox at this point.

I haven't been able to test your branch yet, but unless I am mistaken you would have to refer Google Chrome profiles by the folder name instead of the actual profile name here (see [this comment](https://github.com/johnste/finicky/pull/95#issuecomment-605673725).

The JavaScript file `Finicky/Finicky/finickyConfigAPI.js` is generated from the TypeScript `config-api` project in the repo root so any changes made need to be added there. The profile field would need to be added to the TypeScript types as well as the schema validation.

The pull requests are both pretty similar and I think we can find a good solution that uses parts of both. There haven't been any updates in the last couple of weeks to the other one so I'm not sure it's still being worked on.

I can probably have a look this weekend at combining these efforts.

**Comment by bhedavivek** [comment]
> Hey,
> 
> Thanks for for working on this! There is [another pull request](https://github.com/johnste/finicky/pull/95) adding support for Google Chrome profiles which has a lot of similarity to your approach, though it doesn't attempt to add profile support for Brave or Firefox at this point.

Yes, I've been keeping an eye on that for a while hoping it would get more traction, in the end got impatient and started experimenting for a fix myself. I think my solution provides a more generalized approach. It is inspired by the [ original PR](https://github.com/johnste/finicky/pull/95). I should have probably linked to it or used it as my fork.
> 
> I haven't been able to test your branch yet, but unless I am mistaken you would have to refer Google Chrome profiles by the folder name instead of the actual profile name here (see [this comment](https://github.com/johnste/finicky/pull/95#issuecomment-605673725).
> 

I think with all Chromium browsers that haven't messed with the default CLI options (*cough* Firefox) `--profile-directory=<profile name>` points to the profile directory. However when a user creates a new profile, the directory and the profile have the same name. The directory isn't renamed when the user renames the profile. 

If the `--profile-directory=<profile name>` directory doesn't exist, the browser will just create a directory with that name and generate a profile. However names the profile with the default name 🤦 

I personally being slightly annoyed by that, first created the directory with my intended names and then renamed my profiles. Keeping things consistent.

With Firefox, you can either provide the profile name with `-P ` or provide the profile directory path with `-profile`.

I chose call the config property in Finicky `profile` since you were generally referring to the profile name (or at least what they were originally called)

>
> The JavaScript file `Finicky/Finicky/finickyConfigAPI.js` is generated from the TypeScript `config-api` project in the repo root so any changes made need to be added there. The profile field would need to be added to the TypeScript types as well as the schema validation.
> 

Thanks, for some reason the folder was hidden by XCode and AppCode IDEs, I failed to realize that's where those files were coming from. Naively just updated the JS and experimented locally. I'll update the TS scripts. 

Do I just need to run `npm run build` to regenerate the JS files from the TS files?

> The pull requests are both pretty similar and I think we can find a good solution that uses parts of both. There haven't been any updates in the last couple of weeks to the other one so I'm not sure it's still being worked on.
> 
> I can probably have a look this weekend at combining these efforts.

Thanks for creating this project, has been really useful for me and my personal workflows. Look forward to any suggestions you have to improving this PR.

**Comment by johnste** [comment]
You need yarn to build the js counterpart. After installing all
dependencies by running `yarn` you should just be able to run `yarn build`
to update the bundled js.

I will happily help out any way I can to test this or to fix any issues. It
would be an amazing addition to finicky.

I'm working towards a bigger update pretty soon and if we can get this in
it would be great.

Thanks!

**Comment by bhedavivek** [comment]
Hi, sorry I've not been able to devote time to this PR for the last few weeks. I'll be updating it this week.

**Comment by bhedavivek** [comment]
Hi @johnste 

I've added changes as you requested to the `.ts` files. I see you ended up removing the autogenerated file.

I am wondering if you require any additional changes/unit tests for this to be mergeable. Let me know, I should have more bandwidth available this week to address any required changes.

Thanks,
Vivek

**Comment by bhedavivek** [comment]
I am having trouble running this locally now after the changes made to add coding signing as the development team and `ENABLE_HARDENED_RUNTIME`. How should I go ahead and test?

**Comment by johnste** [comment]
Thanks, I'll check this out.

Did you have to disable Hardened runtime to be able to test? I'm sorry for making it harder but I needed to enable it to be able to noterize the app.

**Comment by bhedavivek** [comment]
I don't think it was the hardened runtime itself, I was just having a hard time building because of the code signing. Since I wasn't using Xcode it was difficult for me to understand how to turn it off.

I eventually gave in and opened Xcode and found the option to build for local testing. (I don't have experience working with Apple app development)

Now that code signing is part of the default build configuration probably should update the command in the README/Wiki to build locally?
```
xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
```

**Comment by johnste** [comment]
Yes, thank you. I will update the wiki.

Finicky is also my one and only XCode project so I'm learning as I go.

**Comment by johnste** [comment]
Hey I had some time to test things out a bit. I didn't have much success so far. I was only able to test Firefox tonight.

I added a handler like so:
```js
    {
      match: /example3/,
      browser: {
        name: "Firefox",
        profile: "simple",          
      },
    },
```

I ran `open http://example.com/example3` in iTerm to test the handler out. So far, all that happens when running command just opens up a new window with the default profile selected and no url set. So that's weird. 

I added a debug output to show the command Finicky generated which is 
`open -a /Applications/Firefox.app -g -n --args -P "simple" http://example.com/example3`. Running _that_ command in iTerm seems to work just fine. So I'm not sure what's going on here.

I tried commenting out `task.waitUntilExit()` like was tested [in the other PR](https://github.com/johnste/finicky/pull/95#issuecomment-597710895), but it didn't seem to have any effect.

I will try to dig more when I have the time again.

**Comment by bhedavivek** [comment]
I've been using a build using this branch for my Brave browser profiles. I think Chromium based browsers will function fine.

With respect to the open command behaving differently, I am assuming its because of its running in a subshell.

If we use native AppKit Classes that control the `open` command (see: https://developer.apple.com/documentation/appkit/nsworkspace/3172702-open) we would have better luck supporting Firefox I think. I could try and hack something together this weekend, but that would mean finicky would only be able to support macos 10.15+

**Comment by bhedavivek** [comment]
Hi, sorry for the lack of updates on this. I found the issue with my changes.
In essence the strategy works fine as we noticed when running commands on the CLI through the terminal.

The issue was two parted:
1. I have the a typo in my bundleId
`org.mozilla.firefox` needs to be `org.mozilla.Firefox` (At some point in my local testing I updated this to the wrong version I don't know why)

2. When I am returning the profileOption I needed to return a String array and not a string literal (kudos my lack of knowledge of swift). I am assuming swift escapes the args passed to process.
So, this needs to be updated from :
```
private func getProfileOption(bundleId: String, profile: String) -> String {
    var profileOption: String {
        switch bundleId {
        case Browser.Firefox.rawValue: return "-P \(profile)"
```

to 

```
private func getProfileOption(bundleId: String, profile: String) -> [String] {
    var profileOption: [String] {
        switch bundleId {
        case Browser.Firefox.rawValue: return ["-P", profile]
```

I tested this locally and should support firefox profiles correctly now.

**Comment by bhedavivek** [comment]
I guess, just needed some fresh eyes.

**Comment by bhedavivek** [comment]
Let me know once this is mergeable, I can go ahead and squash my commits.

**Comment by arefz** [comment]
Thank you so much for working on this @bhedavivek 🥇

**Comment by MoShitrit** [comment]
This is great! Looking forward to see this merged, it'll be super useful.
Thanks for working on this! 😄

**Comment by johnste** [comment]
Hey, I haven't been able to get the time necessary to test this out yet, will do when my schedule opens up. If anyone else wants to help out, building it and trying it out would help a ton!

**Comment by superbrothers** [comment]
I tried this PR with the following settings and found that it works well.

```js
module.exports = {
  defaultBrowser: "Google Chrome",
  handlers: [
    {
      match: (a) => {
        finicky.log(JSON.stringify(a, null, 2));
      },
      browser: "Google Chrome",
    },
    {
      match: ({ keys }) => {
        return keys.command;
      },
      browser: {
        name: "Google Chrome",
        appType: "appName",
        profile: "Default"
      }
    },
    {
      match: ({ keys }) => {
        return keys.shift;
      },
      browser: {
        name: "Google Chrome",
        appType: "appName",
        profile: "Profile 1"
      }
    }
  ]
};
```

@bhedavivek Thank you for a great job!

**Comment by arefz** [comment]
Could we please have this merged? 🙏

**Comment by johnste** [comment]
Will try to get to this soon. I haven't been able to test this yet and I don't want to merge without some thorough testing.

**Comment by bhedavivek** [comment]
Been using this as my local build for the past 3 months with Brave Browser, incase that helps with some confidence with support for Chromium based browser profiles.

**Comment by johnste** [comment]
I have my development setup up and running again, should be able to test this during the next few days.

**Comment by johnste** [comment]
After testing a bit this seems to work well with Chrome (and, like you said, assuming other Chromium based browsers). 

I noted a couple of things:
- If the profile doesn't exist, Chrome will create a new profile
- If the profile name uses a space character, Chrome doesn't appear to be able to match it, and instead creates a new profile

I didn't have much success getting Firefox profiles to work, it appears to work intermittently.

Overall, I'm happy to merge this and start preparing a new release. I think until we have more ability to test Firefox profiles (or other browsers), it makes sense to only officially support Chromium profiles for now.

If you want to look into any other issues or prepare this pull request for merging, feel free to do that and I will merge when you're done. Thank you so much for you work @bhedavivek and sorry for me taking such a long time to get back to you.

**Comment by bhedavivek** [comment]
> After testing a bit this seems to work well with Chrome (and, like you said, assuming other Chromium based browsers).
> 
> I noted a couple of things:
> 
> * If the profile doesn't exist, Chrome will create a new profile
> * If the profile name uses a space character, Chrome doesn't appear to be able to match it, and instead creates a new profile
> 
> I didn't have much success getting Firefox profiles to work, it appears to work intermittently.
> 
> Overall, I'm happy to merge this and start preparing a new release. I think until we have more ability to test Firefox profiles (or other browsers), it makes sense to only officially support Chromium profiles for now.
> 
> If you want to look into any other issues or prepare this pull request for merging, feel free to do that and I will merge when you're done. Thank you so much for you work @bhedavivek and sorry for me taking such a long time to get back to you.

Fixing the chromium profile names with spaces should be easy, I'll escape the profile name for the chromium browsers.

For disabling firefox support, would you like me to comment out the code or remove it completely?

**Comment by johnste** [comment]
Commenting out is fine, maybe add a short explanation as to why/link to
comment maybe

Thanks!

**Comment by bhedavivek** [comment]
I updated the method to only modify the browser command for supported browsers in [commit](https://github.com/johnste/finicky/pull/113/commits/9756d0917431e17991682f037153ce7ccd104c4d)

**Comment by johnste** [comment]
Thank you @bhedavivek for you great work!

**Comment by arefz** [comment]
@johnste 👋  Will you consider pushing out a new release with this anytime soon? 🙏

**Comment by johnste** [comment]
Yes, I'll try to get a release out later tonight.

**Pull request merged**
