### PR TITLE
Managing config file location from the app

### PR DESCRIPTION
**Pull request by leonspok**
Screenshot 2020-10-30 at 20 08 08

In this PR I slightly changed menu items:

* All config-related actions are in a separate submenu
* New option - "Create new". Saves a copy of predefined default config at the specific by user location.
* New option - "Reveal in Finder". Open Finder with config file selected. In case if the file is hidden and Finder is configured not to show hidden files, then Finder window with parent folder will be opened.
* New option - "Replace". Allows you to choose another file to be used as a config.
* Renamed option "Open config" to "Edit". The behaviour is the same.

The location of config file is stored in UserDefaults as bookmark data. This allows us to retain permissions to this file between app launches. Otherwise we would have to show open dialog on each launch. If we can not read bookmark data from UserDefaults or it's missing, the default "~/.finicky.js" location is returned.

### CODE REVIEW

**Comment by johnste** [comment]
Wow, this is amazing! Would love to get this in soon.

I do have some feedback:
- I'm worried that the "replace" and "new config" might potentially confuse users since they change the path read from, and the path isn't visible anywhere. 
     -  Maybe renaming "replace" with "use another file" or something to that effect would help.
     -  I think it would be helpful to log the path finicky is attempting to open to the console whenever trying to read the config
     - If Finicky fails to read the config it would help it displays the path in the error notification
- There's a convention of using ellipsis `...` whenever a menu item opens a dialog window or another application, so if we should change the menu items to reflect that
      - `Config...` -> `Config`
      - `Create new` -> `Create new...` etc  (for all items in the config submenu other than `reload` I guess)
- Love the idea of generating a default config. I'm thinking it would benefit it even further if it also had an example rewrite and matcher (commented out  + with explanations probably). Let me know if you want input on how to do that.

**Comment by leonspok** [comment]
@johnste Thank you for the feedback! I totally agree with it. 

* Aligned menu items naming with the convention about "...". I haven't heard about it before, thank you for telling me. 
* Renamed "Replace config" with "Use another file...". I didn't like my version from the beginning, just couldn't come up with anything better. Your variant sounds much better.
* Added logging of config file's location to the console and informative text in error notifications
* Added an example handler to the default config 
* Also now when your config file disappears Finicky doesn't fall back to the default "~/.finicky.js" location automatically. You need to use "Config > Create new..." or "Use another file...".

**Comment by johnste** [comment]
Sorry, just getting back to this now. Seems like there are conflicts that we should have a look at. I might have time to look at this in a few days.

**Comment by leonspok** [comment]
Hello @johnste! Sorry, I couldn't return to this earlier. I merged latest master from upstream and fixed all conflicts, so it should be ok now.

**Comment by johnste** [comment]
Merged 🎉 

Thank you so much @leonspok !

**Pull request merged**
